version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: colev-twitter-api-mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./basededatos:/data/db
    networks:
      - twitter-api
    ports:
      - 27017:27017

  mongo-express:
    container_name: colev-twitter-api-mongoexpress
    image: mongo-express
    restart: unless-stopped
    networks:
      - twitter-api
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_SERVER: mongodb

networks:
  twitter-api:
