export default {
  'tweet.fields': [
    'attachments',
    'author_id',
    'context_annotations',
    'conversation_id',
    'created_at',
    'entities',
    'geo',
    'id',
    'in_reply_to_user_id',
    'lang',
    'non_public_metrics',
    'public_metrics',
    'organic_metrics',
    'promoted_metrics',
    'possibly_sensitive',
    'referenced_tweets',
    'reply_settings',
    'source',
    'text',
    'withheld',
  ],

  expansions: [
    'referenced_tweets.id',
    'referenced_tweets.id.author_id',
    'author_id,geo.place_id',
    'attachments.media_keys',
    'attachments.poll_ids',
    'entities.mentions.username',
  ],
  'media.fields': [
    'duration_ms',
    'height',
    'media_key',
    'preview_image_url',
    'public_metrics',
    'type',
    'url',
    'width',
    'alt_text',
  ],
  'user.fields': [
    'created_at',
    'description',
    'entities',
    'id',
    'location',
    'name',
    'pinned_tweet_id',
    'profile_image_url',
    'protected',
    'url',
    'username',
    'verified',
    'withheld',
    'public_metrics',
  ],

  'place.fields': ['contained_within', 'country', 'country_code', 'full_name', 'geo', 'id', 'name', 'place_type'],

  'poll.fields': ['duration_minutes', 'end_datetime', 'id', 'options', 'voting_status'],
};
